### ISSUE TITLE
Unable to use Rails 5.2.2

### ISSUE THREAD

**Issue by carltonsmith** [refinery/refinerycms-authentication-devise#44] opened 2019-03-07 14:25 UTC
Getting this in 5.2.2 also

```
Bundler could not find compatible versions for gem "actionmailer":
  In Gemfile:
    rails (~> 5.2.2) was resolved to 5.2.2, which depends on
      actionmailer (= 5.2.2)

    refinerycms-authentication-devise (~> 2.0) was resolved to 2.0.0, which depends on
      actionmailer (< 5.2, >= 5.0.0)
```

**Comment by bricesanchez** [comment] 2019-03-07 15:04
Duplicate of refinery/refinerycms-authentication-devise#39

**Closed by bricesanchez** 2019-03-07 15:04 UTC
